version: '3.8'

services:
  payment-api:
    build:
      context: .
      dockerfile: Payment.Api/Dockerfile
    container_name: payment-api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/payments"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - k6-network

  k6-start:
    image: busybox:latest
    container_name: k6-start-marker
    command: echo "Starting K6 tests..."
    depends_on:
      payment-api:
        condition: service_healthy
    networks:
      - k6-network
    restart: "no"

  k6-runner:
    image: grafana/k6:latest
    container_name: k6-runner
    volumes:
      - ./Payment.IntegrationTest/k6:/scripts
    entrypoint: sh
    command: >
      -c "
        k6 run /scripts/tests/smoke/payment-smoke-test.js;
        k6 run /scripts/tests/load/payment-load-test.js;
        k6 run /scripts/tests/stress/payment-stress-test.js;
        k6 run /scripts/tests/spike/payment-spike-test.js;
        k6 run /scripts/tests/soak/payment-soak-test.js;
        k6 run /scripts/tests/breakpoint/payment-breakpoint-test.js;
        k6 run /scripts/tests/ramp-up/payment-ramp-up-test.js;
        k6 run /scripts/tests/high-load/payment-constant-high-load-test.js;
        k6 run /scripts/tests/mixed/payment-mixed-scenarios-test.js;
        k6 run /scripts/tests/benchmark/payment-performance-benchmark-test.js;
        k6 run /scripts/tests/http-failure/payment-http-timeout-test.js;
        k6 run /scripts/tests/http-failure/payment-connection-limit-test.js;
        k6 run /scripts/tests/http-failure/payment-connection-refused-test.js
      "
    environment:
      - API_URL=http://payment-api:5000
    depends_on:
      k6-start:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    networks:
      - k6-network
    restart: "no"

networks:
  k6-network:
    driver: bridge
